### PR TITLE
Lollipop support

### PR DESCRIPTION
**Pull request by pylerSM**

### CODE REVIEW

**Comment by pylerSM** [comment]
Try to consider:
- refactor/format code
- follow some coding guidelines
- externalize UI strings to strings.xml

to make it better :)

**Comment by pylerSM** [comment]
And:
- update XposedBridge.jar
- remove Android support lib

**Comment by pylerSM** [comment]
- we need new nice icon :)

**Comment by tonyp** [comment]
Why should be update the XposedBridge.jar? That's only needed when you need the new Lollipop APIs like selinux stuff. 

Apart from that the Xposed Bridge should never be compiled into the app, just be referenced.

**Comment by pylerSM** [comment]
Don't required ofc, but good to have latest updates of libs.

**Comment by tonyp** [comment]
For a normal library I'd agree, but when the library only serves as an API reference there's zero need for the update if you don't need the newer APIs.

**Comment by capslock66** [comment]
I didn't fork the code, but I think there is still a problem on the original code :
->Main.java
->public static IPInfo getIPInfo()
->boolean isIPv4 = InetAddressUtils.isIPv4Address(sAddr);

InetAddressUtils was deprecated in API level 22 (Android 5.1)
Here is the isIPv4Address code that can be used directly :

import java.util.regex.Pattern;
private static final Pattern IPV4_PATTERN = Pattern.compile("^(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)(\\.(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)){3}$");
public static boolean isIPv4Address(final String input)
{
return IPV4_PATTERN.matcher(input).matches();
}

**Comment by pylerSM** [comment]
Did you test it?

Deprecated but not removed in 5.1 (will be removed in M). I see no issues, people on XDA say it works on 5.1. 

Fork the code, send patch.

**Comment by capslock66** [comment]
I can't test it, because I d'ont use it.
I check sometimes the code to see how he progress so I can fix my proper module (reverse tethering)

**Comment by pylerSM** [comment]
Ok, added own isIPv4Address method.

Btw, where we can find your module? possibly open source?

**Comment by pylerSM** [comment]
@lemonsqueeze bump

**Comment by capslock66** [comment]
Here is the code I just published
https://github.com/capslock66/HackConnectivityService

**Comment by pylerSM** [comment]
@lemonsqueeze Bump again. @capslock66 why your module is not in repo? :)

**Comment by capslock66** [comment]
@lemonsqueeze : My module is designed to work with Reverse Tethering. Can't leave alone in the repository.

**Comment by lemonsqueeze** [comment]
Been away for a while, i'll take a look...

**Comment by pylerSM** [comment]
I thought about some code cleanup (adress things I had mentioned above). But I am not a designer to make new module icon, can somebody do it please?

**Comment by pylerSM** [comment]
Maybe even add option to hide/show app in launcher.

**Comment by lemonsqueeze** [comment]
I'll think about it for next release (not much time atm)
Thanks

**Pull request merged**
